### ISSUE TITLE
Combined annotations breaks the undo method

### ISSUE THREAD

**Issue by Firesphere** [axyr/silverstripe-ideannotator#34]
When combining the existing docblocks, with the annotator docblocks, we end up with something like this:
```
/**
 * Description of the class
 * StartGeneratedWithDataObjectAnnotator
 * {Annotations here}
 * EndGeneratedWithDataObjectAnnotator
 */
```
Currently, the annotator removes the start and close blocks for docblocks as well, or does nothing. In the example above, it won't do nothing.

I suggest, only removing the actual docblock part, instead of also removing the opening and closing of the docblocks.

Although, this might cause issues with classes, having these kind of docblocks:
```
/**
 */
```
I would consider it less harmful than possibly destroying the class declarations.

**Comment by axyr** [comment]
This is introduced by adding the docblocks into existing docblocks right?

**Comment by Firesphere** [comment]
It's specifically the remove method. See the regex, it looks for anything between
```
/**
 * StartAnnotations
 * {anything here}
 * EndAnnotations
 */
```
and tries to remove the entire block. Thereby, possibly removing a closing tag (`*/`), unrelated to the generator.

**Comment by axyr** [comment]
This will be fixed when we use phpDocumentor and be able to merge existing docblocks..

**Comment by axyr** [comment]
Ok. so the annotator uses the StartGenerated and EndGenerated to recognize the generated code.
This is done, so it is possible to UNDO the generation action.

This assumes that the generated docblock is not altered afterwards.

Using phpDocumentor will fix a lot of things : 

  - Generation will work when more the 1 DataObject exists in 1 file #19 
  - Generation of Page_Controller docblocks #1 
  - Detect existing docblocks #3 

To make phpDocumentor work we need to drop the StartGeneratedWithDataObjectAnnotator method, since we will merge Tags into an existing docblock.

I added the undo action for 'TO BE SURE', bu I dont think we really need it when the generation just works ok.

So we can fix : 
  - StartGeneratedWithDataObjectAnnotator #41 
  -  and this ticket #34 

What do you think?
Should we drop the UNDO method and instead maybe have an option to write a generated file to a new MyClass.php.annotated file or something?

**Comment by Firesphere** [comment]
I'm going to have a look tomorrow, but from this description.... Epic!

I'm unsure about dropping the tags though, because they might be needed for updating or undo. That's just a quick thought without looking at the code though :)
I would personally stick to writing it to the file itself. That's how the IDE recognizes it. Moving it to a "annotated" file, will still require user actions. I don't think that's the right way to go.
I need to have a look at PHPDocumentor as well, before I can give some real constructive feedback on this. Dropping the start/end tag would, in my opinion, not be the optimal way to go, unless the system checks for being in dev-mode, to make sure there's at least not something "destroyed" by accident on a live site?

Nice work! This looks like a great step forward on the module. And with a bit of tweaking, generating documentation from the docblocks might even sound not that far fetched!

p.s.
Don't overwork yourself!

**Comment by axyr** [comment]
I want to add it as an option to write the changes to a seperate file, so users can inspect the results once, and from there just write the docblocks to the files itself.

But maybe we could add this later. Everybody that uses this module works with a IDE that supports file history and I think it is save to assume everybody work in a version repo by now. So if something goes wrong with the generation it is easily fixed..

This module should never be used on a live website. If users do that, its their fault. The documentation is clear about that and the module is disabled by default, so users have to "double opt-in" the functionality.

phpDocumentor parses the existing docblocks and add the propertie/method/etc tags with existing tags.

I use this Laravel package as an example : 
https://github.com/barryvdh/laravel-ide-helper/blob/master/src/Console/ModelsCommand.php

It works pretty great on Laravel Eloquent models.

**Comment by axyr** [comment]
your right, we should check for dev mode...

**Comment by axyr** [comment]
Stricter dev mode checking is now applied with 84d763e76f83aa1b00e0481ae1e66fb332bd6022
I also removed the undo functionality. I have never used it and it does not work when someone alters the docblocks which is a pretty common action when adding your own comments to it.

So the fix is removing the not 100% working functionality in favor of getting something better...
