### ISSUE TITLE
DBInt and DBFloat

### ISSUE THREAD

**Issue by axyr** [axyr/silverstripe-ideannotator#56]
These are SS4 classes right?

Can we remove these until this is actual needed?

**Comment by Firesphere** [comment]
They can be removed. But it shouldn't break the current 3.x situation, so I don't see why actually?
Are they breaking for you? Because it's just testing the existence. Also, they might exist in 3.x if someone applied the 327 patch.

**Comment by axyr** [comment]
Because it makes my IDE raise a flag about non existing classes ;)

**Comment by Firesphere** [comment]
Haha, if that's the reason, I'd say, don't change it.

Being compatible with 4 is good, right? Once 3 is deprecated, you'll get 
the same with the old classnames ;)

As long as it doesn't break the build, I prefer to keep it in there.

**Comment by axyr** [comment]
autocompletion and getting green checkmarks in my IDE is why I started this module ;)

should we not tag for SS4 ?

**Comment by axyr** [comment]
but if you really think we should keep it, we keep it.

**Comment by Firesphere** [comment]
It's a big edge case. Maybe for now remove them, but add an class exists?
In theory, it shouldn't break on 3, because it would be false. But admitted, the class not being there isn't a nice way. Basically ignoring the option... Not good.

On the other hand, removing it will break builds that rely on lekoala/327 for SS3.2x to work on PHP7.
I'll have a deep thought about this. I can't find any "this is the best way to go" option actually.

**Comment by axyr** [comment]
lets keep it.

**Comment by Firesphere** [comment]
I guess that solves it :D
